# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	if Vagrant.has_plugin? "vagrant-vbguest"
		config.vbguest.no_install  = true
		config.vbguest.auto_update = false
		config.vbguest.no_remote   = true
	end
	config.vm.define :servidorUbuntu do |servidorUbuntu|
		servidorUbuntu.vm.box = "bento/ubuntu-20.04"
		servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
		servidorUbuntu.vm.hostname = "deliveryserver"
		servidorUbuntu.vm.provision "file", source: "final-test", destination: "/home/vagrant/final-test"
		servidorUbuntu.vm.provision "shell", path: "script_docker.sh"
		servidorUbuntu.vm.provider "virtualbox" do |v|
			v.name = "dockerUbuntuCICD"
			v.memory = 4096
			v.cpus = 2
		end
	end
end